"""项目全局常量定义 - 消除代码中的魔法数字"""

# === 视频处理 ===
DEFAULT_VIDEO_INTERVAL = 1800  # 视频分段时长（秒），即30分钟
DEFAULT_ANALYSIS_INTERVAL = 10  # 帧分析间隔（秒）
DEFAULT_BUFFER_DURATION = 11  # 滑窗分析时长（秒）
DEFAULT_WS_RETRY_INTERVAL = 3  # WebSocket重连间隔（秒）
DEFAULT_MAX_WS_QUEUE = 100  # WebSocket消息队列最大容量
DEFAULT_JPEG_QUALITY = 70  # JPEG压缩质量（0-100）
DEFAULT_FRAME_SAMPLE_INTERVAL = 5  # 帧采样间隔（秒）
DEFAULT_STREAM_FRAME_INTERVAL = 5  # 视频流抽帧间隔（秒）

# === 并发与性能 ===
DEFAULT_MAX_CONCURRENT_STREAMS = 50  # 最大并发流数
DEFAULT_MAX_CONCURRENT_AI_CALLS = 150  # 最大并发AI调用数
DEFAULT_STREAM_BUFFER_BATCH_SIZE = 200  # 流数据批量处理大小
DEFAULT_STREAM_BUFFER_FLUSH_INTERVAL = 7  # 流缓冲区刷新间隔（秒）

# === FFmpeg 解码器 ===
FFMPEG_ANALYZE_DURATION = 5000000  # FFmpeg默认分析时长（微秒）：5秒
FFMPEG_PROBE_SIZE = 10000000  # FFmpeg默认探测大小（字节）：10MB
FFMPEG_MAX_DELAY = 500000  # FFmpeg最大延迟（微秒）：0.5秒
FFMPEG_STREAM_ANALYZE_DURATION = 10000000  # 流分析时长（微秒）：10秒
FFMPEG_STREAM_PROBE_SIZE = 20000000  # 流探测大小（字节）：20MB
FFMPEG_DECODE_THREADS = 4  # FFmpeg解码线程数
FFMPEG_PROCESS_BUFFER_SIZE = 10 ** 8  # FFmpeg进程stdout缓冲区（100MB）
FFMPEG_DEFAULT_FPS = 25.0  # FFmpeg默认帧率
FFMPEG_DEFAULT_WIDTH = 1920  # 默认视频宽度
FFMPEG_DEFAULT_HEIGHT = 1080  # 默认视频高度
FFMPEG_FRAME_QUEUE_SIZE = 30  # FFmpeg帧队列大小
FFMPEG_RECONNECT_INTERVAL = 5  # FFmpeg重连间隔（秒）
FFMPEG_DECODER_ALIVE_TIMEOUT = 120.0  # 解码器存活判断超时（秒）
FFMPEG_CONSECUTIVE_READ_FAILURES_LIMIT = 10  # 连续读取失败阈值，超过则重启

# === 帧质量检测 ===
DEFAULT_FRAME_WARMUP_COUNT = 30  # 预热帧数：启动时丢弃前N帧
DEFAULT_FRAME_QUALITY_MIN_SCORE = 70.0  # 帧最低质量分数
DEFAULT_FRAME_SHARPNESS_MIN = 400.0  # 帧最低清晰度
FRAME_MEAN_BLACK_THRESHOLD = 5  # 全黑帧判定：平均像素值低于此值
FRAME_MEAN_WHITE_THRESHOLD = 250  # 全白帧判定：平均像素值高于此值
FRAME_GRAY_MEAN_LOW = 100  # 灰色帧判定：亮度下限
FRAME_GRAY_MEAN_HIGH = 160  # 灰色帧判定：亮度上限
FRAME_GRAY_STD_THRESHOLD = 20  # 灰色帧判定：对比度阈值
FRAME_MIN_STD_THRESHOLD = 5  # 纯色帧判定：最低标准差
FRAME_MIN_DIMENSION = 100  # 有效帧最小宽/高（像素）
FRAME_MAX_DIMENSION = 10000  # 有效帧最大宽/高（像素）
FRAME_SIZE_MISMATCH_TOLERANCE = 3  # 帧尺寸不匹配容忍次数

# === MJPEG 流媒体 ===
MJPEG_FPS_TARGET = 15  # MJPEG目标帧率
MJPEG_FRAME_QUEUE_SIZE = 5  # MJPEG帧队列大小
MJPEG_JPEG_QUALITY = 90  # MJPEG JPEG压缩质量
MJPEG_CLEANUP_INTERVAL = 300  # 内存清理间隔（秒），即5分钟
MJPEG_FRAME_MEMORY_LIMIT = 50 * 1024 * 1024  # 单帧内存限制（50MB）
MJPEG_RECONNECT_WARMUP_FRAMES = 15  # 重连后预热帧数
MJPEG_BUFFER_CLEAR_INTERVAL = 30  # 缓冲区定期清空间隔（秒）
MJPEG_NO_FRAME_SLEEP = 0.033  # 无帧时等待间隔（秒），约30FPS
MJPEG_OPENCV_BUFFER_CLEAR_COUNT = 5  # OpenCV缓冲区清空次数
MJPEG_LOG_INTERVAL = 100  # 日志输出间隔（每N帧）
MJPEG_STATUS_LOG_INTERVAL = 300  # 状态日志输出间隔（每N帧）
MJPEG_QUALITY_CHECK_INTERVAL = 5  # 质量检查间隔（每N帧）
MJPEG_STRICT_MODE_WARMUP_LIMIT = 20  # 严格模式生效帧数（预热后N帧内）

# === MJPEG OpenCV连接策略参数 ===
OPENCV_UDP_ANALYZE_DURATION = 2000000  # UDP策略分析时长（微秒）
OPENCV_UDP_PROBE_SIZE = 5000000  # UDP策略探测大小（字节）
OPENCV_TCP_ANALYZE_DURATION = 3000000  # TCP策略分析时长（微秒）
OPENCV_TCP_PROBE_SIZE = 8000000  # TCP策略探测大小（字节）
OPENCV_DEFAULT_ANALYZE_DURATION = 1000000  # 默认后端分析时长（微秒）
OPENCV_DEFAULT_PROBE_SIZE = 3000000  # 默认后端探测大小（字节）

# === 严格模式帧检测 ===
STRICT_LOW_VARIANCE_THRESHOLD = 20  # 块方差低阈值
STRICT_LOW_VARIANCE_BLOCK_LIMIT = 12  # 低方差块数量上限（超过75%为异常）
STRICT_MAX_BRIGHTNESS_DEVIATION = 80  # 块亮度最大偏离值

# === 流帧分析器 ===
STREAM_FRAME_SELECTOR_INTERVAL = 15  # 帧质量选择器选择间隔
STREAM_FRAME_SELECTOR_BUFFER_SIZE = 15  # 帧质量选择器缓冲区大小
STREAM_HEALTH_LOG_INTERVAL = 100  # 解码器健康日志间隔（每N帧）
STREAM_QUALITY_STATS_LOG_INTERVAL = 300  # 质量过滤统计日志间隔（每N帧）
STREAM_CPU_SLEEP_INTERVAL = 0.05  # CPU避让间隔（秒）

# === AI 分析 ===
AI_RESILIENT_TIMEOUT = 30  # 容错AI分析超时（秒）
AI_RESILIENT_MAX_RETRIES = 3  # 容错AI分析最大重试次数

# === 数据库连接池 ===
DEFAULT_DB_POOL_SIZE = 30  # 核心连接池大小
DEFAULT_DB_MAX_OVERFLOW = 50  # 最大溢出连接数
DEFAULT_DB_POOL_TIMEOUT = 45  # 获取连接超时（秒）
DEFAULT_DB_POOL_RECYCLE = 1800  # 连接回收时间（秒），即30分钟

# === 存储 ===
DEFAULT_MAX_FILE_SIZE_MB = 500  # 文件大小上限（MB）
DEFAULT_CLEANUP_INTERVAL_HOURS = 24  # 清理间隔（小时）
DEFAULT_FILE_RETENTION_DAYS = 30  # 文件保留天数

# === API 请求 ===
DEFAULT_REQUEST_TIMEOUT = 60.0  # API请求超时（秒）

# === 健康监控 ===
DEFAULT_TASK_HEALTH_CHECK_INTERVAL = 300  # 任务健康检查间隔（秒），即5分钟
DEFAULT_STREAM_HEALTH_CHECK_INTERVAL = 600  # 视频流健康检查间隔（秒），即10分钟
DEFAULT_RETRY_DELAY_BASE = 300  # 基础重试延迟（秒），即5分钟
DEFAULT_MAX_RETRY_DELAY = 3600  # 最大重试延迟（秒），即1小时
DEFAULT_MAX_CONSECUTIVE_FAILURES = 5  # 最大连续失败次数
